Import ActionList during __init__
loonghao/photoshop-python-api pull request #131
Opened 2022-03-19 10:29 UTC by MrTeferi

Could we add this to __init__ so you can call ps.ActionList() while doing photoshop actions?

2022-03-20 00:27 UTC, loonghao commented
@MrTeferi 
You can use the following command line to format codes.

## setting up the dev environment
```
pip install poetry
```
```
poetry install
```
## format code
```
poetry run black photoshop
```
```
poetry run isort photoshop
```
## commit code
```shell
git add photoshop/api/__init__.py
```
https://github.com/commitizen-tools/commitizen
```
cz commit 
```

2022-03-20 00:32 UTC, loonghao requested changes

2022-03-20 00:32 UTC, loonghao commented on photoshop/api/__init__.py
> +    "ActionList",
We also need to add `ActionList` in [`session.py`](https://github.com/loonghao/photoshop-python-api/blob/main/photoshop/session.py#L124)

2022-04-06 02:21 UTC, MrTeferi reviewed
Looks good to me!

2022-04-12 05:50 UTC, loonghao commented
@MrTeferi We also need to update the current MR git commit message need to use `cz commit`
https://github.com/commitizen-tools/commitizen

because the CI will be using this commit message auto `bump-version` and auto-generate changelogs
![image](https://user-images.githubusercontent.com/13111745/162889541-0cd827c0-68a1-4378-9121-5815b6ffa119.png)

2022-04-13 06:44 UTC, closed without merging